# Generated by Django 5.1.6 on 2026-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0005_alter_takenlessons_options_logpracticescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpracticescore',
            name='lesson',
            field=models.CharField(max_length=150, null=True, verbose_name='Lesson'),
        ),
    ]
