# Generated by Django 5.1.6 on 2026-02-19 05:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0006_logpracticescore_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogPracticeScore',
            new_name='PracticeScore',
        ),
    ]
