# Generated by Django 5.1.6 on 2026-02-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0007_rename_logpracticescore_practicescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicescore',
            name='total_questions',
            field=models.IntegerField(default=20),
        ),
    ]
