# Generated by Django 5.1.6 on 2026-02-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0008_practicescore_total_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
