# Generated by Django 5.1.6 on 2026-02-21 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0009_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.PositiveIntegerField()),
                ('wrong', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField(default=30)),
                ('correct_percentage', models.PositiveSmallIntegerField(help_text='0–100')),
                ('time_spent_seconds', models.PositiveIntegerField(help_text='Total seconds spent on the test')),
                ('time_spent_display', models.CharField(help_text="Human-readable e.g. '12m 34s'", max_length=20)),
                ('avg_time_per_question_seconds', models.FloatField(help_text='Average seconds per question')),
                ('test_taken_at', models.CharField(help_text="Locale string from the browser e.g. '2/21/2026, 3:45:00 PM'", max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions_json_formatted', models.TextField(verbose_name='Questions JSON')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='math_test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Math Test Result',
                'verbose_name_plural': 'Math Test Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PracticeScore',
        ),
    ]
