# Generated by Django 5.1.6 on 2026-02-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0010_mathtestresult_delete_practicescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, verbose_name='Language')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.AddField(
            model_name='mathtestresult',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='math_test_results', to='mathematics.lessons'),
            preserve_default=False,
        ),
    ]
