# Generated by Django 5.1.6 on 2026-02-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0011_lessons_delete_languages_mathtestresult_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterField(
            model_name='mathtestresult',
            name='questions_json_formatted',
            field=models.JSONField(verbose_name='Questions JSON'),
        ),
    ]
