# Generated by Django 5.1.6 on 2026-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0012_alter_lessons_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtestresult',
            name='questions_json_formatted',
            field=models.JSONField(null=True, verbose_name='Questions JSON'),
        ),
    ]
