# Generated by Django 5.1.6 on 2026-02-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0014_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
