# Generated by Django 5.1.6 on 2026-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0015_pendinguser_first_name_pendinguser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
