# Generated by Django 5.1.6 on 2026-02-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0016_pendinguser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
