# Generated by Django 5.1.6 on 2026-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0019_usermonitoringproxy_alter_country_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='Anonymous', max_length=100)),
                ('message_type', models.CharField(choices=[('recommendation', 'Recommendation'), ('problem', 'Problem Report')], default='recommendation', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ReportsAndRecommendations',
        ),
    ]
