# Generated by Django 5.1.6 on 2026-03-18 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_homework_homeworkattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomeworkDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_doc_id', models.CharField(max_length=255, unique=True)),
                ('google_doc_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homework_docs', to='classroom.classroom')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_docs', to='classroom.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homework_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
