# Generated by Django 5.1.6 on 2026-03-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_studenthomeworkfile_delete_studenthomeworkdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomeworkfile',
            name='editor_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
