# Generated by Django 5.1.6 on 2026-03-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_studenthomeworkfile_editor_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomeworkfile',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studenthomeworkfile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
